name: Linter

on: [push, pull_request]

env:
  OPEN_UCX_LINK: https://github.com/openucx/ucx
  OPEN_UCX_BRANCH: master
jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends wget lsb-core software-properties-common
        sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
        sudo apt-get install -y --no-install-recommends doxygen doxygen-latex clang-tidy-11 bear
    - name: Get UCX
      run: git clone ${OPEN_UCX_LINK} -b ${OPEN_UCX_BRANCH} /tmp/ucx
    - name: Build UCX
      run: |
        cd /tmp/ucx && ./autogen.sh
        ./contrib/configure-release --without-java --disable-numa --prefix $PWD/install
        make -j install
    - uses: actions/checkout@v1
    - name: Build UCC
      run: |
        ./autogen.sh
        CC=clang-11 CXX=clang++-11 ./configure --prefix=/tmp/ucc/install --with-ucx=/tmp/ucx/install
        bear --cdb /tmp/compile_commands.json make
    - name: Run clang-tidy
      run: |
        echo "Workspace: ${GITHUB_WORKSPACE}"
        cd ${GITHUB_WORKSPACE}
        run-clang-tidy-11 -p /tmp/
